import { Table,TableBody,TableCell,TableHead,TableHeader,TableRow } from '@/components/ui/table';
import { numberText as n,SOURCES,type SuccessResult } from '@/lib/hydraulics';

export function Formulas({r}:{r:SuccessResult|null}) {
  return <section id="formulas" className="panel formula-panel">
    <div className="panel-heading"><div><span className="eyebrow">CALCULATION NOTES</span><h2>公式與計算過程</h2></div><span className="quiet">SI 制 · Darcy f</span></div>
    <p className="support">單一路徑、穩態、不可壓縮、充滿流道；使用整段平均液溫。直管長度不含彎頭弧長。</p>
    <div className="formula-grid">
      <article><span className="step-number">01</span><h3>截面與水力直徑</h3><p className="equation">圓管：A = πD²/4，Dh = D<br/>矩形：A = ab，Dh = 2ab/(a+b)</p>{r&&<p className="substitution">A = {n(r.g.area*1e6)} mm²<br/>Dh = {n(r.g.dh*1000)} mm</p>}</article>
      <article><span className="step-number">02</span><h3>流速與雷諾數</h3><p className="equation">Q [m³/s] = Q [L/min] / 60,000<br/>v = Q/A，ν = μ/ρ，Re = ρvDh/μ</p>{r&&<p className="substitution">v = {n(r.q,8)} / {n(r.g.area,8)} = {n(r.v)} m/s<br/>Re = {n(r.p.rho,2)} × {n(r.v,4)} × {n(r.g.dh,5)} / {n(r.p.mu,7)} = {n(r.re,1)}</p>}</article>
      <article><span className="step-number">03</span><h3>摩擦係數</h3><p className="equation">層流圓管：f = 64/Re<br/>層流矩形：f = Po/Re</p><p className="equation">α = min(a,b)/max(a,b)<br/>Po = 96(1 − 1.3553α + 1.9467α² − 1.7012α³ + 0.9564α⁴ − 0.2537α⁵)</p><p className="equation">Colebrook：<br/>1/√f = −2 log₁₀[ε/(3.7Dh) + 2.51/(Re√f)]</p><p className="fine-print">Re ≤ 2300 用層流解析式；2300–4000 用層流值與 Re = 4000 紊流端點作平滑插值 s = 3t² − 2t³，t = (Re − 2300)/1700；Re ≥ 4000 用選定紊流模型。矩形紊流以 Dh 等效。</p>{r&&<p className="substitution">ε/Dh = {n(r.ed,6)}<br/>{r.f.name}：f = {r.re===0?'—（無流動）':n(r.f.f,6)}</p>}</article>
      <article><span className="step-number">04</span><h3>直管壓降</h3><p className="equation">pv = ρv²/2<br/>Δp直管 = f × (L/Dh) × pv</p>{r&&<p className="substitution">pv = {n(r.p.rho,2)} × {n(r.v,4)}² / 2 = {n(r.dynamic)} Pa<br/>Δp = {n(r.f.f,6)} × ({n(r.i.length)}/{n(r.g.dh,5)}) × {n(r.dynamic)} = <strong>{n(r.straight)} Pa</strong></p>}</article>
      <article className="formula-wide"><span className="step-number">05</span><h3>彎頭與局部損失</h3><p className="equation">θ = 角度 × π/180，r = R/Dh<br/>K彎 = fθr + (0.10 + 2.4f)sin(θ/2) + 6.6f[√sin(θ/2) + sin(θ/2)] / r^(4θ/π)<br/>Δp彎頭 = Σ(nK彎) × pv，Δp附加 = K附加 × pv</p><p className="fine-print">自動彎頭採 Rennels，適用圓滑、等截面彎管；此 App 限 Re ≥ 4000、R/Dh &gt; 0.5。K 已含彎頭弧長摩擦，勿重複加到直管長度。矩形為 Dh 近似。手動 K 應涵蓋整個彎頭，且以本流道平均流速為基準；需對應實際 Re 與流體條件。</p>{r&&<Table className="engineering-table"><TableHeader><TableRow><TableHead>角度</TableHead><TableHead>數量</TableHead><TableHead>{r.i.bendMode==='auto'?'R/Dh':'來源'}</TableHead><TableHead>單個 K</TableHead><TableHead>合計 Pa</TableHead></TableRow></TableHeader><TableBody>{r.bends.map(b=><TableRow key={b.angle}><TableCell>{b.angle}°</TableCell><TableCell>{b.count}</TableCell><TableCell>{r.i.bendMode==='auto'?n(b.ratio):'手動'}</TableCell><TableCell>{b.count===0?'未使用':n(b.k,5)}</TableCell><TableCell>{n(b.dp)}</TableCell></TableRow>)}</TableBody></Table>}</article>
      <article><span className="step-number">06</span><h3>總壓降與液柱高度</h3><p className="equation">Δp總 = Δp直管 + Δp彎頭 + Δp附加<br/>H液體 = Δp總/(ρg)<br/>P液壓 = Δp總 × Q，g = 9.80665 m/s²</p>{r&&<p className="substitution">Δp總 = {n(r.straight)} + {n(r.bendDrop)} + {n(r.extra)} = <strong>{n(r.total)} Pa</strong><br/>H = {n(r.head)} m（目前液體）</p>}<p className="fine-print">壓降是流阻損失，不是入口絕對壓力。此處未計高度差、歧管、快接、閥件或泵曲線；附加配件可合併填入 K。液壓功率不等於泵電功率。並聯時不可把各支路壓降直接相加。</p></article>
    </div>
    <details className="technical-details"><summary>查看原工具的四種摩擦係數公式</summary><div className="expanded-content"><p>以下 f 均為 Darcy 摩擦係數，e = ε/Dh。</p><p className="equation">Moody：f = 0.0055[1 + (20,000e + 10⁶/Re)^(1/3)]</p><p className="equation">Churchill：f = 8[(8/Re)¹² + (A+B)^(−3/2)]^(1/12)<br/>A = [2.457 ln(1/((7/Re)^0.9 + 0.27e))]¹⁶<br/>B = (37,530/Re)¹⁶</p><p className="equation">Zigrang–Sylvester（第二式）：<br/>A₅ = e/3.7 + 13/Re<br/>A₆ = e/3.7 − (5.02/Re)log₁₀A₅<br/>f = [−2log₁₀(e/3.7 − (5.02/Re)log₁₀A₆)]⁻²</p><p className="equation">Romeo et al.：<br/>C = (e/7.7918)^0.9924 + [5.3326/(208.815+Re)]^0.9345<br/>B = e/3.827 − (4.567/Re)log₁₀C<br/>f = [−2log₁₀(e/3.7065 − (5.0272/Re)log₁₀B)]⁻²</p><p className="fine-print">「四式較大值」只在符合各公式範圍的模型中取大值，並非實際壓降的最大保證。Moody：4000 ≤ Re ≤ 10⁸、e ≤ 0.01；Zigrang–Sylvester：4000 ≤ Re ≤ 10⁸、4×10⁻⁵ ≤ e ≤ 0.05；Romeo：本工具採 4000 ≤ Re ≤ 1.5×10⁸、e ≤ 0.05。層流統一使用截面對應解析式。</p></div></details>
    <div id="sources" className="sources"><h3>物性與公式來源</h3><p>EG 50% 與 PG 25% 都是<strong>體積濃度 vol%</strong>。以 Dynalene 原廠表列值作工程參考，並不代表所有品牌的配方；重量濃度 wt% 或指定冷卻液請使用手動物性。</p><p>內建溫度 0–90 °C；密度線性插值、動力黏度對數插值。ρ(T) = (1−w)ρ₀ + wρ₁；ln μ(T) = (1−w)ln μ₀ + w ln μ₁。1 lb/ft³ = 16.018463 kg/m³；1 cP = 1 mPa·s = 0.001 Pa·s。</p>{r&&!r.i.custom&&<p className="substitution">目前使用 {n(r.p.t0,2)}–{n(r.p.t1,2)} °C 表列區間，w = {n(r.p.weight,4)}。</p>}<div className="source-links"><a href={SOURCES.eg50} target="_blank" rel="noreferrer">Dynalene EG 原廠物性表 ↗</a><a href={SOURCES.pg25} target="_blank" rel="noreferrer">Dynalene PG 原廠物性表 ↗</a><a href={SOURCES.friction} target="_blank" rel="noreferrer">Fluids 摩擦係數公式與範圍 ↗</a><a href={SOURCES.bends} target="_blank" rel="noreferrer">Rennels 彎頭公式 ↗</a><a href={SOURCES.rectangular} target="_blank" rel="noreferrer">矩形層流長寬比修正 ↗</a></div></div>
  </section>;
}
